[package]
name = "chain_observers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = { version = "0.16.0"}
tokio = { version = "1", features = ["full"] }